// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:flutter_todos/data/services/models/todo_dto.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(TodoDtoAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(TodoDtoAdapter());
  }
}
